######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 29 15:24:58 2022
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src src/connect src/main
INCLUDEPATH += . src/connect

# Input
HEADERS += src/connect/connect.hpp
SOURCES += src/server.cpp src/connect/connect.cpp src/main/main.cpp
